# Generated by Django 3.2 on 2021-06-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, max_length=512, null=True, upload_to='images/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(verbose_name='Ширина изображения')),
                ('height', models.IntegerField(verbose_name='Высота изображения')),
                ('file', models.ImageField(blank=True, max_length=512, null=True, upload_to='images_sized/', verbose_name='Изображение с изменённым размером')),
                ('image', models.OneToOneField(db_tablespace=True, on_delete=django.db.models.deletion.CASCADE, to='images_app.image')),
            ],
        ),
    ]
