# Generated by Django 3.2 on 2021-06-13 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=512, upload_to='images/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(verbose_name='Ширина картинки')),
                ('height', models.IntegerField(verbose_name='Высота картинки')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images_app.image')),
            ],
        ),
    ]
