# Generated by Django 3.2 on 2021-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='images/', verbose_name='Картинка'),
        ),
    ]
