# Generated by Django 3.2 on 2021-06-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesize',
            name='file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='images_sized/', verbose_name='Изображение с изменённым размером'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='imagesize',
            name='height',
            field=models.IntegerField(verbose_name='Высота изображения'),
        ),
        migrations.AlterField(
            model_name='imagesize',
            name='image',
            field=models.OneToOneField(db_tablespace=True, on_delete=django.db.models.deletion.CASCADE, to='images_app.image'),
        ),
        migrations.AlterField(
            model_name='imagesize',
            name='width',
            field=models.IntegerField(verbose_name='Ширина изображения'),
        ),
    ]
